package com.ak_tech.bb.enums;

public enum ResultValues {
    //Quote TAble
    Value,
    ExchangeRate,
    ValueForCustoms,
    AES,
    RIV,
    AC,
    Form1,
    CustomsDuties,
    CustomsMPF,
    CustomsHMF,
    EntryFee,
    ClassificationFee,
    Bond,
    BondUnderwritingFee,
    CustomsISF,
    DutyDisbursementFee,
    NAFTA,
    ABIFee,
    DotEpa,
    ImporterRegistrationFee,
    OneTimePAPSExemption,
    EManifest,
    CustomsGST,
    CustomsPST,
    CustomsHST,
    CustomsQST,
    CustomsClearance,
    CustomsClearanceGST,
    CustomsClearancePST,
    CustomsClearanceHST,
    CustomsClearanceQST,
    GrandTotalFees,
    AdministrationFee,
}